name: Trigger auto deployment for container-app-ba3hmbnmpla64

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-ba3hmbnmpla64-AutoDeployTrigger-3ad9d941-49f7-46a0-9741-be40773a9702.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPBA3HMBNMPLA64_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPBA3HMBNMPLA64_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPBA3HMBNMPLA64_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryba3hmbnmpla64.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPBA3HMBNMPLA64_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPBA3HMBNMPLA64_REGISTRY_PASSWORD }}
          containerAppName: container-app-ba3hmbnmpla64
          resourceGroup: expresssample90159e68
          imageToBuild: containerregistryba3hmbnmpla64.azurecr.io/container-app-ba3hmbnmpla64:${{ github.sha }}
          


